package com.rodrigos01.aiaudiobook.core

/**
 * Languages supported by the backend's speech generation when creating a title. Mirrors
 * https://ai.google.dev/gemini-api/docs/speech-generation#languages
 */
enum class Language(val displayName: String, val code: String) {
    AFRIKAANS("Afrikaans", "af"),
    ALBANIAN("Albanian", "sq"),
    AMHARIC("Amharic", "am"),
    ARABIC("Arabic", "ar"),
    ARMENIAN("Armenian", "hy"),
    AZERBAIJANI("Azerbaijani", "az"),
    BANGLA("Bangla", "bn"),
    BASQUE("Basque", "eu"),
    BELARUSIAN("Belarusian", "be"),
    BULGARIAN("Bulgarian", "bg"),
    BURMESE("Burmese", "my"),
    CATALAN("Catalan", "ca"),
    CEBUANO("Cebuano", "ceb"),
    CHINESE_MANDARIN("Chinese (Mandarin)", "cmn"),
    CROATIAN("Croatian", "hr"),
    CZECH("Czech", "cs"),
    DANISH("Danish", "da"),
    DUTCH("Dutch", "nl"),
    ENGLISH("English", "en"),
    ESTONIAN("Estonian", "et"),
    FILIPINO("Filipino", "fil"),
    FINNISH("Finnish", "fi"),
    FRENCH("French", "fr"),
    GALICIAN("Galician", "gl"),
    GEORGIAN("Georgian", "ka"),
    GERMAN("German", "de"),
    GREEK("Greek", "el"),
    GUJARATI("Gujarati", "gu"),
    HAITIAN_CREOLE("Haitian Creole", "ht"),
    HEBREW("Hebrew", "he"),
    HINDI("Hindi", "hi"),
    HUNGARIAN("Hungarian", "hu"),
    ICELANDIC("Icelandic", "is"),
    INDONESIAN("Indonesian", "id"),
    ITALIAN("Italian", "it"),
    JAPANESE("Japanese", "ja"),
    JAVANESE("Javanese", "jv"),
    KANNADA("Kannada", "kn"),
    KONKANI("Konkani", "kok"),
    KOREAN("Korean", "ko"),
    LAO("Lao", "lo"),
    LATIN("Latin", "la"),
    LATVIAN("Latvian", "lv"),
    LITHUANIAN("Lithuanian", "lt"),
    LUXEMBOURGISH("Luxembourgish", "lb"),
    MACEDONIAN("Macedonian", "mk"),
    MAITHILI("Maithili", "mai"),
    MALAGASY("Malagasy", "mg"),
    MALAY("Malay", "ms"),
    MALAYALAM("Malayalam", "ml"),
    MARATHI("Marathi", "mr"),
    MONGOLIAN("Mongolian", "mn"),
    NEPALI("Nepali", "ne"),
    NORWEGIAN_BOKMAL("Norwegian (Bokmål)", "nb"),
    NORWEGIAN_NYNORSK("Norwegian (Nynorsk)", "nn"),
    ODIA("Odia", "or"),
    PASHTO("Pashto", "ps"),
    PERSIAN("Persian", "fa"),
    POLISH("Polish", "pl"),
    PORTUGUESE("Portuguese", "pt"),
    PUNJABI("Punjabi", "pa"),
    ROMANIAN("Romanian", "ro"),
    RUSSIAN("Russian", "ru"),
    SERBIAN("Serbian", "sr"),
    SINDHI("Sindhi", "sd"),
    SINHALA("Sinhala", "si"),
    SLOVAK("Slovak", "sk"),
    SLOVENIAN("Slovenian", "sl"),
    SPANISH("Spanish", "es"),
    SWAHILI("Swahili", "sw"),
    SWEDISH("Swedish", "sv"),
    TAMIL("Tamil", "ta"),
    TELUGU("Telugu", "te"),
    THAI("Thai", "th"),
    TURKISH("Turkish", "tr"),
    UKRAINIAN("Ukrainian", "uk"),
    URDU("Urdu", "ur"),
    VIETNAMESE("Vietnamese", "vi");

    companion object {
        fun fromCode(code: String): Language? = entries.find { it.code == code }
    }
}
